spring:
  profile: dev
  kafka:
    bootstrap-servers: host.docker.internal:9092
    consumer:
      group-id: sample-group-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  data:
    mongodb:
      uri: mongodb://root:M0rd0r!@host.docker.internal:27017/persons?ssl=false&authSource=admin&retryWrites=true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  topic-name: sampletopic
  messages-per-request: 10
