spring:
  profile: dev
  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      acks: 1
      client-id: kafka-producer-1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 2
      properties:
        spring:
          json:
            add:
              type:
                headers: false


server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  topic-name: sampletopic
  messages-per-request: 10
